Added octokit gem in Gemfile.local
octokit gem is required to run rake task,
(https://github.com/tdiary/tdiary-core/pull/573)
but octokit gem is in development group.

So, `docker biuld -t minimum2scp/magellan-tdiary:0.1.4pre1 .` failed:

```
Step 15 : RUN cd /usr/src/app && rake assets:copy
 ---> Running in 24c8454d2d92
rake aborted!
LoadError: cannot load such file -- octokit
/usr/src/app/lib/tdiary/tasks/release.rake:4:in `require'
/usr/src/app/lib/tdiary/tasks/release.rake:4:in `<top (required)>'
/usr/src/app/lib/tdiary/tasks.rb:1:in `load'
/usr/src/app/lib/tdiary/tasks.rb:1:in `block in <top (required)>'
/usr/src/app/lib/tdiary/tasks.rb:1:in `each'
/usr/src/app/lib/tdiary/tasks.rb:1:in `<top (required)>'
/usr/src/app/Rakefile:4:in `require'
/usr/src/app/Rakefile:4:in `<top (required)>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
ERROR: Service 'tdiary' failed to build: The command '/bin/sh -c cd /usr/src/app && rake assets:copy' returned a non-zero code: 1
```

Reported this problem to https://github.com/tdiary/tdiary-core/issues/575